### ISSUE TITLE
Greek typos

### ISSUE THREAD

**Issue by dajare** [robinwhittleton/edgar-allan-poe_short-fiction#1]
I hope reporting them in this format is clear and helpful:

εϛτιν > εστιν [ 2x in lines 74 and 75

- https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/blob/3ac3496d7ffbb745ec9de3d6cf2720601259b90f/src/epub/text/bon-bon.xhtml#L74

- https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/blob/3ac3496d7ffbb745ec9de3d6cf2720601259b90f/src/epub/text/bon-bon.xhtml#L75

---

https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/blob/4f4e9742cdef87e7dd405d478d5401e99302663e/src/epub/text/how-to-write-a-blackwood-article.xhtml#L72

Ανερο > Ανερ ο

---

https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/blob/876e04a50abedff2e99e45bca07abab3a1ebd289/src/epub/text/morella.xhtml#L13

μουο ειδεζ αιει ου >  μονοειδεϛ αιει ον

---

https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/blob/3ac3496d7ffbb745ec9de3d6cf2720601259b90f/src/epub/text/endnotes.xhtml#L153

μουσιχη > μουσικη

https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/blob/3ac3496d7ffbb745ec9de3d6cf2720601259b90f/src/epub/text/endnotes.xhtml#L159

πνρ > πυρ

---

https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/blob/876e04a50abedff2e99e45bca07abab3a1ebd289/src/epub/text/the-assignation.xhtml#L36

ΔΑΞΜ > ΛΑΣΜ

ΓΕΔΑΞΜΑ > ΓΕΛΑΣΜΑ

---

https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/blob/92ba3f7b941f6870259848ac4a9fa4f649e61402/src/epub/text/silence.xhtml#L17

’Ευδονσιυ ρορεων κοδ’υφαι τε και φαραγγεζ > ’Ευδουσιν δ’ ορεων κορυφαι τε και φαραγγες

https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/blob/92ba3f7b941f6870259848ac4a9fa4f649e61402/src/epub/text/silence.xhtml#L19

Πρωνεζ τε και χαραδραι. > Πρωνες τε και χαραδραι.

---

https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/blob/876e04a50abedff2e99e45bca07abab3a1ebd289/src/epub/text/the-colloquy-of-monos-and-una.xhtml#L90

μουσυιη > μουσικη

---

https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/blob/5bc5a6d797638ace6e6f4babb06161c062cfbdab/src/epub/text/the-conversation-of-eiros-and-charmion.xhtml#L13

Πνρ σοι προσοισω. > Πυρ σοι προσοισω.

**Comment by robinwhittleton** [comment]
Amazing, thanks so much for checking these. I fixed them in https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/commit/25ca0251f714bf80570c964d8cb195c67ac9770a.
