### ISSUE TITLE
Is it our practice to change dipthong ligatures?

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/edgar-allan-poe_short-fiction#2]
Maybe I'm wrong, but I thought it was our practice to change æ to ae, œ to oe, etc? There's quite a lot of these in the ligature form, admittedly it looks as though only in foreign language phrases.

**Comment by robinwhittleton** [comment]
Appropriate section is https://standardebooks.org/manual/1.1.0/8-typography#8.6 . I thought we didn’t change in names either, but it looks like I misinterpreted that. So non-English ligatures changed in https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/commit/f00bab1e935735bfb7f7995029f89ea4fcc3e824.
