### ISSUE TITLE
Being very pendantic ! An <em> which would be better as <i>?

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/edgar-allan-poe_short-fiction#3]
In "How To Write a Blackwood Article", on line 40, I would have thought `<em>The Epidendrum Flos Aeris</em>` would be better as `<i>The Epidendrum Flos Aeris</i>` since it's not emphasised speech.

**Comment by robinwhittleton** [comment]
I like pedantic 😄 Fixed in https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/commit/2eaf888a06223bfcbd79e332992f0e37884712c7.
