### ISSUE TITLE
datetime tags where year is unknown

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/edgar-allan-poe_short-fiction#4]
In The Unparalleled Adventure of Hans Pfall" you have for example: `<time datetime="--04-18">April 18th</time>`  If I'm reading the spec for datetime correctly, this should just be `<time datetime="04-18">April 18th</time>` etc.

**Comment by drgrigg** [comment]
I'm also puzzled (probably due to my lack of full understanding of CSS) why Hans' letter isn't indented the same way as other letters. At least, it isn't in Apple's Books app.

**Comment by drgrigg** [comment]
Oh, scratch the latter comment. You've set it that way in local.css of course.

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/commit/47ee989c181971cca3db66a08f0c371ae62b7596. I think I’d read the ISO standard for this format? But looking at HTML5.2’s spec for this you’re right: https://www.w3.org/TR/html52/infrastructure.html#yearless-dates
